services:
  - type: web
    name: microsoft-teams-backend
    env: node
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        sync: false
      - key: MS_CLIENT_ID
        sync: false
      - key: MS_CLIENT_SECRET
        sync: false
      - key: MS_TENANT_ID
        sync: false
      - key: MS_REDIRECT_URI
        value: https://teams-95o4.onrender.com/auth/callback
      - key: POST_LOGIN_REDIRECT
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1